# Generated by Django 5.1.3 on 2024-11-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_location', models.CharField(max_length=255)),
                ('loading_date', models.DateTimeField()),
                ('unloading_location', models.CharField(max_length=255)),
                ('unloading_date', models.DateTimeField()),
                ('cargo_details', models.TextField(blank=True, null=True)),
                ('weight_kg', models.FloatField(default=0.0)),
                ('distance_km', models.FloatField(default=0.0)),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('best_offer', models.BooleanField(default=False)),
                ('ref_number', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
    ]
