# Generated by Django 5.1.3 on 2024-11-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_location', models.CharField(max_length=255)),
                ('unloading_location', models.CharField(max_length=255)),
                ('distance_km', models.FloatField()),
                ('price', models.FloatField()),
                ('date_received', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
