# Generated by Django 5.1.3 on 2025-01-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='loading_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='loading_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='unloading_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
