# Generated by Django 5.1.3 on 2025-03-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_unloading_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='recommended_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
