# Generated by Django 5.1.3 on 2024-11-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
