# Generated by Django 5.1.3 on 2025-01-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_loading_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='unloading_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
